platform :ios, '9.0'

target 'URLSession' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PocketSVG'
  pod 'Alamofire'

  # Pods for URLSession

  target 'URLSessionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'URLSessionUITests' do
    # Pods for testing
  end

end
